name: Deploy npm

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  cancel-previous:
    name: "Cancel Previous Runs"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  deploy:
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16.10.0"
          registry-url: https://registry.npmjs.org/

      - name: Set npm credentials
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> $HOME/.npmrc

      - name: Install package
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Npm Run Test
        run: npm run test

      - name: Deploy on master branch
        if: github.ref == 'refs/heads/master'
        uses: codfish/semantic-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
